In [2]:
import keras

Using TensorFlow backend.


In [3]:
from keras import backend as K

cfg = K.tf.ConfigProto()
cfg.gpu_options.allow_growth = True
K.set_session(K.tf.Session(config=cfg))

In [4]:
import random
random.uniform(0.01, 1)

0.6508231734825147

In [5]:
import random


def white (img):
    x=random.uniform(0.1, 2)
    return img**x
    

In [6]:
from keras.layers import Activation ,Conv2D ,BatchNormalization , Dense ,Dropout ,Flatten ,MaxPool2D
from keras.models import Sequential

In [7]:
model = Sequential([
            BatchNormalization(axis=1, input_shape=(150,300,1)),
            Conv2D(32,(3,3), activation='relu'),
            BatchNormalization(axis=1),
            Conv2D(32,(3,3), activation='relu'),
            MaxPool2D((2,2)),
            BatchNormalization(axis=1),
            Conv2D(64,(3,3), activation='relu'),
            BatchNormalization(axis=1),
            Conv2D(64,(3,3), activation='relu'),
            MaxPool2D((2,2)),
            BatchNormalization(axis=1),
            Conv2D(128,(3,3), activation='relu'),
            BatchNormalization(axis=1),
            Conv2D(128,(3,3), activation='relu'),
            MaxPool2D((2,2)),
            BatchNormalization(axis=1),
            Conv2D(128,(3,3), activation='relu'),
            BatchNormalization(axis=1),
            Conv2D(128,(3,3), activation='relu'),
            MaxPool2D((2,2)),
            Flatten(),
            Dense(1024, activation='relu'),
            BatchNormalization(),
            Dropout (0.4),
            Dense(1024, activation='relu'),
            BatchNormalization(),
            Dropout (0.4),
            Dense(4, activation='softmax')
        ])

In [8]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization_1 (Batch (None, 150, 300, 1)       600       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 148, 298, 32)      320       
_________________________________________________________________
batch_normalization_2 (Batch (None, 148, 298, 32)      592       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 146, 296, 32)      9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 73, 148, 32)       0         
_________________________________________________________________
batch_normalization_3 (Batch (None, 73, 148, 32)       292       
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 71, 146, 64)       18496     
__________

In [9]:
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image
gen=image.ImageDataGenerator(rotation_range=15,shear_range=0.1 ,channel_shift_range=0.2 ,width_shift_range=0.4 , height_shift_range=0.25)
gen1=image.ImageDataGenerator()

In [16]:
batch_size=30

train= gen.flow_from_directory('train', target_size=(150,300),
                class_mode='categorical', shuffle=True, batch_size=batch_size, color_mode='grayscale')

Found 5820 images belonging to 4 classes.


In [17]:
val= gen1.flow_from_directory('val', target_size=(150,300),
                class_mode='categorical', shuffle=False, batch_size=batch_size, color_mode='grayscale')

Found 1098 images belonging to 4 classes.


In [12]:
from keras.optimizers import Adam
model.compile(Adam(lr=0.00001), loss='categorical_crossentropy', metrics=['accuracy'])

In [13]:
#model.load_weights ('new3.h5')

In [14]:
batch_size=30
model.fit_generator(train, steps_per_epoch=5820/batch_size, epochs=3, 
                            validation_data=val, validation_steps=1098/batch_size)

Epoch 1/3
291/291 [==============================] - 256s - loss: 2.0888 - acc: 0.2985 - val_loss: 1.7112 - val_acc: 0.2386
Epoch 2/3
291/291 [==============================] - 230s - loss: 1.9623 - acc: 0.3100 - val_loss: 1.6396 - val_acc: 0.3233
Epoch 3/3
291/291 [==============================] - 263s - loss: 1.9401 - acc: 0.3232 - val_loss: 1.7554 - val_acc: 0.2696


In [19]:
batch_size=30
model.optimizer.lr=0.1
model.fit_generator(train, steps_per_epoch=5820/batch_size, epochs=10, 
                            validation_data=val, validation_steps=1098/batch_size)

Epoch 1/10
194/194 [==============================] - 193s - loss: 1.8731 - acc: 0.3373 - val_loss: 1.6035 - val_acc: 0.3424
Epoch 2/10
194/194 [==============================] - 193s - loss: 1.8235 - acc: 0.3497 - val_loss: 1.5251 - val_acc: 0.3324
Epoch 3/10
194/194 [==============================] - 194s - loss: 1.7680 - acc: 0.3608 - val_loss: 1.6223 - val_acc: 0.3424
Epoch 4/10
194/194 [==============================] - 193s - loss: 1.7384 - acc: 0.3668 - val_loss: 1.4793 - val_acc: 0.3434
Epoch 5/10
194/194 [==============================] - 192s - loss: 1.7352 - acc: 0.3660 - val_loss: 1.4884 - val_acc: 0.3370
Epoch 6/10
194/194 [==============================] - 192s - loss: 1.6866 - acc: 0.3797 - val_loss: 1.4812 - val_acc: 0.3461
Epoch 7/10
194/194 [==============================] - 193s - loss: 1.6438 - acc: 0.3957 - val_loss: 1.4990 - val_acc: 0.3716
Epoch 8/10
194/194 [==============================] - 195s - loss: 1.6472 - acc: 0.3942 - val_loss: 1.6019 - val_acc: 0.3670


In [20]:
model.save_weights ('new1.h5')

In [39]:
model.fit_generator(train, steps_per_epoch=5820/batch_size, epochs=10, 
                            validation_data=val, validation_steps=1098/batch_size)

Epoch 1/10
194/194 [==============================] - 193s - loss: 1.5869 - acc: 0.4165 - val_loss: 1.7296 - val_acc: 0.3297
Epoch 2/10
194/194 [==============================] - 193s - loss: 1.5828 - acc: 0.4175 - val_loss: 1.6501 - val_acc: 0.3370
Epoch 3/10
194/194 [==============================] - 193s - loss: 1.5636 - acc: 0.4263 - val_loss: 1.6737 - val_acc: 0.3270
Epoch 4/10
194/194 [==============================] - 193s - loss: 1.5469 - acc: 0.4230 - val_loss: 1.6092 - val_acc: 0.3169
Epoch 5/10
194/194 [==============================] - 193s - loss: 1.5577 - acc: 0.4253 - val_loss: 1.7017 - val_acc: 0.3434
Epoch 6/10
194/194 [==============================] - 248s - loss: 1.5334 - acc: 0.4251 - val_loss: 1.6863 - val_acc: 0.3151
Epoch 7/10
194/194 [==============================] - 271s - loss: 1.4864 - acc: 0.4366 - val_loss: 1.7245 - val_acc: 0.3224
Epoch 8/10
194/194 [==============================] - 194s - loss: 1.4951 - acc: 0.4529 - val_loss: 1.6605 - val_acc: 0.3306


In [42]:
model.save_weights ('new3.h5')

In [41]:
model.optimizer.lr=0.01
model.fit_generator(train, steps_per_epoch=5820/batch_size, epochs=10, 
                            validation_data=val, validation_steps=1098/batch_size)

Epoch 1/10
194/194 [==============================] - 260s - loss: 1.4401 - acc: 0.4636 - val_loss: 1.7125 - val_acc: 0.3224
Epoch 2/10
194/194 [==============================] - 453s - loss: 1.4200 - acc: 0.4694 - val_loss: 1.6519 - val_acc: 0.3042
Epoch 3/10
194/194 [==============================] - 457s - loss: 1.4442 - acc: 0.4560 - val_loss: 1.6924 - val_acc: 0.3233
Epoch 4/10
194/194 [==============================] - 416s - loss: 1.4180 - acc: 0.4766 - val_loss: 1.7037 - val_acc: 0.3179
Epoch 5/10
194/194 [==============================] - 483s - loss: 1.4154 - acc: 0.4608 - val_loss: 1.5949 - val_acc: 0.3188
Epoch 6/10
194/194 [==============================] - 513s - loss: 1.4070 - acc: 0.4684 - val_loss: 1.6403 - val_acc: 0.3233
Epoch 7/10
194/194 [==============================] - 335s - loss: 1.4109 - acc: 0.4753 - val_loss: 1.6806 - val_acc: 0.2914
Epoch 8/10
194/194 [==============================] - 509s - loss: 1.3639 - acc: 0.4799 - val_loss: 1.7003 - val_acc: 0.3015


In [ ]:
model.optimizer.lr=0.01
model.fit_generator(train, steps_per_epoch=5820/batch_size, epochs=10, 
                            validation_data=val, validation_steps=1098/batch_size)

Epoch 1/10
194/194 [==============================] - 264s - loss: 1.3554 - acc: 0.4890 - val_loss: 1.6253 - val_acc: 0.3078
Epoch 2/10
194/194 [==============================] - 305s - loss: 1.2895 - acc: 0.5005 - val_loss: 1.7211 - val_acc: 0.3015
Epoch 3/10
 67/194 [=========>....................] - ETA: 169s - loss: 1.3101 - acc: 0.4920

In [ ]:
model.optimizer.lr=0.001
model.fit_generator(train, steps_per_epoch=2387/batch_size, epochs=5, 
                            validation_data=val, validation_steps=594/batch_size)

In [ ]:
model.fit_generator(train, steps_per_epoch=2387/batch_size, epochs=5, 
                            validation_data=val, validation_steps=594/batch_size)

In [ ]:
   
model.optimizer.lr=0.1
for i in range (4,9):
    model.fit_generator(train, steps_per_epoch=2387/batch_size, epochs=5, 
                            validation_data=val, validation_steps=594/batch_size)
    model.save_weights ('new{x}.h5'.format(x=i))

In [ ]:
model.optimizer.lr=0.001
for i in range (9,15):
    model.fit_generator(train, steps_per_epoch=2387/batch_size, epochs=5, 
                            validation_data=val, validation_steps=594/batch_size)
    model.save_weights ('new{x}.h5'.format(x=i))

In [ ]:
model.load_weights('new10.h5')

In [22]:
test = gen1.flow_from_directory('test', target_size=(150,300),
                class_mode='categorical', shuffle=False, batch_size=1 ,color_mode='grayscale')

Found 200 images belonging to 4 classes.


In [23]:
test.class_indices

{'al': 0, 'bl': 1, 'lotr': 2, 'ra': 3}

In [24]:
pre=model.predict_generator(test,200)

In [25]:
test.class_indices

{'al': 0, 'bl': 1, 'lotr': 2, 'ra': 3}

In [26]:
files = test.filenames

In [35]:
mistake=0
doubt=0
file=[]
file1=[]
correct=0
num=0
for x in pre : 
    
    if (x[0]<0.6 and x[0]>0.4) or (x[1]<0.6 and x[1]>0.4) or (x[2]<0.6 and x[2]>0.4) or (x[3]<0.6 and x[3]>0.4)  : 
        doubt+=1
        print (x , "doubt")
        file1.append (files[num])
    else:
        if num<50:
            if x[0]<0.3: 
                mistake+=1
                print (x,num)
                file.append (files[num])
            else : correct+=1
        elif num<100:
            if x[1]<0.3: 
                mistake+=1
                print (x,num) 
                file.append (files[num])
            else : correct+=1
        elif num<150:
            if x[2]<0.3: 
                mistake+=1
                print (x,num) 
                file.append (files[num])
            else : correct+=1
                
        else:
            if x[3]<0.3: 
                mistake+=1
                print (x,num) 
                file.append (files[num])
            else : correct+=1
    num+=1
    
all=correct+mistake

[ 0.04020891  0.60409611  0.19727623  0.15841873] 1
[ 0.14861488  0.00274551  0.81311899  0.03552062] 2
[ 0.01790603  0.04217943  0.10800786  0.83190674] 3
[ 0.04685045  0.2602011   0.67316294  0.01978547] 4
[ 0.01539489  0.62541139  0.33566627  0.02352746] 5
[ 0.02486388  0.40741289  0.53508168  0.03264153] doubt
[ 0.00649297  0.10666455  0.04708645  0.83975595] 7
[ 0.00431231  0.00741366  0.00980984  0.97846413] 8
[ 0.29605886  0.00806052  0.63602901  0.05985165] 9
[ 0.02192388  0.21098268  0.7381075   0.02898596] 10
[ 0.01331131  0.12890297  0.0313895   0.82639617] 11
[ 0.00313375  0.01175865  0.03136178  0.95374578] 12
[ 0.06378714  0.09285598  0.78941131  0.05394561] 13
[ 0.0289786   0.1233722   0.82145548  0.02619367] 14
[ 0.20751768  0.45738548  0.21756464  0.11753217] doubt
[ 0.01885102  0.30381632  0.58762282  0.08970993] doubt
[ 0.01150945  0.86461782  0.09013187  0.03374089] 17
[ 0.04079349  0.06996413  0.877451    0.01179141] 18
[ 0.00150929  0.00703889  0.00780757  0.98364

In [36]:
correct

35

In [37]:
doubt/(all+doubt)

0.445

In [38]:
mistake

76

In [ ]:
image.load_img ('newtest/'+files[54])